import type BinaryReader from '../BinaryReader'
import type { WorldProperties } from '../types'

export enum GameMode {
  NormalMode,
  ExpertMode,
  MasterMode,
  CreativeMode,
}

export default function parseHeader(reader: BinaryReader, world: WorldProperties) {
  const isV140 = world.version >= 225
  const isV144 = world.version >= 269

  return {
    mapName: reader.readString(),
    seedText: reader.readString(),
    worldGeneratorVersion: reader.readBytes(8),
    guid: reader.readBytes(16),
    worldId: reader.readInt32(),
    leftWorld: reader.readInt32(),
    rightWorld: reader.readInt32(),
    topWorld: reader.readInt32(),
    bottomWorld: reader.readInt32(),
    maxTilesY: reader.readInt32(),
    maxTilesX: reader.readInt32(),
    gameMode: (isV140 ? reader.readInt32() : 0) as GameMode,
    drunkWorld: isV140 ? reader.readBoolean() : false,
    getGoodWorld: world.version >= 227 ? reader.readBoolean() : false,
    getTenthAnniversaryWorld: world.version >= 238 ? reader.readBoolean() : false,
    dontStarveWorld: world.version >= 239 ? reader.readBoolean() : false,
    notTheBeesWorld: world.version >= 241 ? reader.readBoolean() : false,
    remixWorld: world.version >= 249 ? reader.readBoolean() : false,
    noTrapsWorld: world.version >= 266 ? reader.readBoolean() : false,
    zenithWorld: world.version >= 267 ? reader.readBoolean() : false,
    expertMode: !isV140 ? reader.readBoolean() : false,
    creationTime: reader.readBytes(8),
    moonType: reader.readUInt8(),
    treeX: [reader.readInt32(), reader.readInt32(), reader.readInt32()],
    treeStyle: [reader.readInt32(), reader.readInt32(), reader.readInt32(), reader.readInt32()],
    caveBackX: [reader.readInt32(), reader.readInt32(), reader.readInt32()],
    caveBackStyle: [reader.readInt32(), reader.readInt32(), reader.readInt32(), reader.readInt32()],
    iceBackStyle: reader.readInt32(),
    jungleBackStyle: reader.readInt32(),
    hellBackStyle: reader.readInt32(),
    spawnTileX: reader.readInt32(),
    spawnTileY: reader.readInt32(),
    worldSurface: reader.readFloat64(),
    rockLayer: reader.readFloat64(),
    tempTime: reader.readFloat64(),
    tempDayTime: reader.readBoolean(),
    tempMoonPhase: reader.readInt32(),
    tempBloodMoon: reader.readBoolean(),
    tempEclipse: reader.readBoolean(),
    dungeonX: reader.readInt32(),
    dungeonY: reader.readInt32(),
    crimson: reader.readBoolean(),
    downedBoss1: reader.readBoolean(),
    downedBoss2: reader.readBoolean(),
    downedBoss3: reader.readBoolean(),
    downedQueenBee: reader.readBoolean(),
    downedMechBoss1: reader.readBoolean(),
    downedMechBoss2: reader.readBoolean(),
    downedMechBoss3: reader.readBoolean(),
    downedMechBossAny: reader.readBoolean(),
    downedPlantBoss: reader.readBoolean(),
    downedGolemBoss: reader.readBoolean(),
    downedSlimeKing: reader.readBoolean(),
    savedGoblin: reader.readBoolean(),
    savedWizard: reader.readBoolean(),
    savedMech: reader.readBoolean(),
    downedGoblins: reader.readBoolean(),
    downedClown: reader.readBoolean(),
    downedFrost: reader.readBoolean(),
    downedPirates: reader.readBoolean(),
    shadowOrbSmashed: reader.readBoolean(),
    spawnMeteor: reader.readBoolean(),
    shadowOrbCount: reader.readUInt8(),
    altarCount: reader.readInt32(),
    hardMode: reader.readBoolean(),
    afterPartyOfDoom: world.version >= 257 ? reader.readBoolean() : false,
    invasionDelay: reader.readInt32(),
    invasionSize: reader.readInt32(),
    invasionType: reader.readInt32(),
    invasionX: reader.readFloat64(),
    slimeRainTime: reader.readFloat64(),
    sundialCooldown: reader.readUInt8(),
    tempRaining: reader.readBoolean(),
    tempRainTime: reader.readInt32(),
    tempMaxRain: reader.readFloat32(),
    oreTier1: reader.readInt32(),
    oreTier2: reader.readInt32(),
    oreTier3: reader.readInt32(),
    setBG0: reader.readUInt8(),
    setBG1: reader.readUInt8(),
    setBG2: reader.readUInt8(),
    setBG3: reader.readUInt8(),
    setBG4: reader.readUInt8(),
    setBG5: reader.readUInt8(),
    setBG6: reader.readUInt8(),
    setBG7: reader.readUInt8(),
    cloudBGActive: reader.readInt32(),
    numClouds: reader.readInt16(),
    windSpeed: reader.readFloat32(),
    anglerWhoFinishedToday: reader.readArray(reader.readInt32(), reader.readString),
    savedAngler: reader.readBoolean(),
    anglerQuest: reader.readInt32(),
    savedStylist: reader.readBoolean(),
    savedTaxCollector: reader.readBoolean(),
    savedGolfer: isV140 ? reader.readBoolean() : false,
    invasionSizeStart: reader.readInt32(),
    tempCultistDelay: reader.readInt32(),
    killCount: reader.readArray(reader.readInt16(), reader.readInt32),
    fastForwardTimeToDawn: reader.readBoolean(),
    downedFishron: reader.readBoolean(),
    downedMartians: reader.readBoolean(),
    downedAncientCultist: reader.readBoolean(),
    downedMoonlord: reader.readBoolean(),
    downedHalloweenKing: reader.readBoolean(),
    downedHalloweenTree: reader.readBoolean(),
    downedChristmasIceQueen: reader.readBoolean(),
    downedChristmasSantank: reader.readBoolean(),
    downedChristmasTree: reader.readBoolean(),
    downedTowerSolar: reader.readBoolean(),
    downedTowerVortex: reader.readBoolean(),
    downedTowerNebula: reader.readBoolean(),
    downedTowerStardust: reader.readBoolean(),
    TowerActiveSolar: reader.readBoolean(),
    TowerActiveVortex: reader.readBoolean(),
    TowerActiveNebula: reader.readBoolean(),
    TowerActiveStardust: reader.readBoolean(),
    LunarApocalypseIsUp: reader.readBoolean(),
    tempPartyManual: reader.readBoolean(),
    tempPartyGenuine: reader.readBoolean(),
    tempPartyCooldown: reader.readInt32(),
    tempPartyCelebratingNPCs: reader.readArray(reader.readInt32(), reader.readInt32),
    Temp_Sandstorm_Happening: reader.readBoolean(),
    Temp_Sandstorm_TimeLeft: reader.readInt32(),
    Temp_Sandstorm_Severity: reader.readFloat32(),
    Temp_Sandstorm_IntendedSeverity: reader.readFloat32(),
    savedBartender: reader.readBoolean(),
    DD2Event_DownedInvasionT1: reader.readBoolean(),
    DD2Event_DownedInvasionT2: reader.readBoolean(),
    DD2Event_DownedInvasionT3: reader.readBoolean(),
    setBG8: isV140 ? reader.readUInt8() : 0,
    setBG9: isV140 ? reader.readUInt8() : 0,
    setBG10: isV140 ? reader.readUInt8() : 0,
    setBG11: isV140 ? reader.readUInt8() : 0,
    setBG12: isV140 ? reader.readUInt8() : 0,
    combatBookWasUsed: isV140 ? reader.readBoolean() : false,
    lanternNightCooldown: isV140 ? reader.readInt32() : 0,
    lanternNightGenuine: isV140 ? reader.readBoolean() : false,
    lanternNightManual: isV140 ? reader.readBoolean() : false,
    lanternNightNextNightIsGenuine: isV140 ? reader.readBoolean() : false,
    treeTopsVariations: isV140 ? reader.readArray(reader.readInt32(), reader.readInt32) : [],
    forceHalloweenForToday: isV140 ? reader.readBoolean() : false,
    forceXMasForToday: isV140 ? reader.readBoolean() : false,
    savedOreTierCopper: isV140 ? reader.readInt32() : 0,
    savedOreTierIron: isV140 ? reader.readInt32() : 0,
    savedOreTierSilver: isV140 ? reader.readInt32() : 0,
    savedOreTierGold: isV140 ? reader.readInt32() : 0,
    boughtCat: isV140 ? reader.readBoolean() : false,
    boughtDog: isV140 ? reader.readBoolean() : false,
    boughtBunny: isV140 ? reader.readBoolean() : false,
    downedEmpressOfLight: isV140 ? reader.readBoolean() : false,
    downedQueenSlime: isV140 ? reader.readBoolean() : false,
    downedDeerclops: world.version >= 240 ? reader.readBoolean() : false,
    unlockedSlimeBlueSpawn: isV144 ? reader.readBoolean() : false,
    unlockedMerchantSpawn: isV144 ? reader.readBoolean() : false,
    unlockedDemolitionistSpawn: isV144 ? reader.readBoolean() : false,
    unlockedPartyGirlSpawn: isV144 ? reader.readBoolean() : false,
    unlockedDyeTraderSpawn: isV144 ? reader.readBoolean() : false,
    unlockedTruffleSpawn: isV144 ? reader.readBoolean() : false,
    unlockedArmsDealerSpawn: isV144 ? reader.readBoolean() : false,
    unlockedNurseSpawn: isV144 ? reader.readBoolean() : false,
    unlockedPrincessSpawn: isV144 ? reader.readBoolean() : false,
    combatBookVolumeTwoWasUsed: isV144 ? reader.readBoolean() : false,
    peddlersSatchelWasUsed: isV144 ? reader.readBoolean() : false,
    unlockedSlimeGreenSpawn: isV144 ? reader.readBoolean() : false,
    unlockedSlimeOldSpawn: isV144 ? reader.readBoolean() : false,
    unlockedSlimePurpleSpawn: isV144 ? reader.readBoolean() : false,
    unlockedSlimeRainbowSpawn: isV144 ? reader.readBoolean() : false,
    unlockedSlimeRedSpawn: isV144 ? reader.readBoolean() : false,
    unlockedSlimeYellowSpawn: isV144 ? reader.readBoolean() : false,
    unlockedSlimeCopperSpawn: isV144 ? reader.readBoolean() : false,
    fastForwardTimeToDusk: isV144 ? reader.readBoolean() : false,
    moondialCooldown: isV144 ? reader.readUInt8() : 0,
  }
}
