import type BinaryReader from '../BinaryReader'
import type { WorldProperties } from '../types'

export enum GameMode {
  NormalMode,
  ExpertMode,
  MasterMode,
  CreativeMode,
}

export default function parseHeader(reader: BinaryReader, world: WorldProperties) {
  const isV140 = world.version >= 225
  const isV144 = world.version >= 269

  return {
    mapName: reader.readString(),
    seedText: reader.readString(),
    worldGeneratorVersion: reader.readBytes(8),
    guid: reader.readBytes(16),
    worldId: reader.readInt32(),
    leftWorld: reader.readInt32(),
    rightWorld: reader.readInt32(),
    topWorld: reader.readInt32(),
    bottomWorld: reader.readInt32(),
    maxTilesY: reader.readInt32(),
    maxTilesX: reader.readInt32(),
    gameMode: Number(isV140 && reader.readInt32()) as GameMode,
    drunkWorld: isV140 && reader.readBoolean(),
    getGoodWorld: world.version >= 227 && reader.readBoolean(),
    getTenthAnniversaryWorld: world.version >= 238 && reader.readBoolean(),
    dontStarveWorld: world.version >= 239 && reader.readBoolean(),
    notTheBeesWorld: world.version >= 241 && reader.readBoolean(),
    remixWorld: world.version >= 249 && reader.readBoolean(),
    noTrapsWorld: world.version >= 266 && reader.readBoolean(),
    zenithWorld: world.version >= 267 && reader.readBoolean(),
    expertMode: !isV140 && reader.readBoolean(),
    creationTime: reader.readBytes(8),
    moonType: reader.readUInt8(),
    treeX: [reader.readInt32(), reader.readInt32(), reader.readInt32()],
    treeStyle: [reader.readInt32(), reader.readInt32(), reader.readInt32(), reader.readInt32()],
    caveBackX: [reader.readInt32(), reader.readInt32(), reader.readInt32()],
    caveBackStyle: [reader.readInt32(), reader.readInt32(), reader.readInt32(), reader.readInt32()],
    iceBackStyle: reader.readInt32(),
    jungleBackStyle: reader.readInt32(),
    hellBackStyle: reader.readInt32(),
    spawnTileX: reader.readInt32(),
    spawnTileY: reader.readInt32(),
    worldSurface: reader.readFloat64(),
    rockLayer: reader.readFloat64(),
    tempTime: reader.readFloat64(),
    tempDayTime: reader.readBoolean(),
    tempMoonPhase: reader.readInt32(),
    tempBloodMoon: reader.readBoolean(),
    tempEclipse: reader.readBoolean(),
    dungeonX: reader.readInt32(),
    dungeonY: reader.readInt32(),
    crimson: reader.readBoolean(),
    downedBoss1: reader.readBoolean(),
    downedBoss2: reader.readBoolean(),
    downedBoss3: reader.readBoolean(),
    downedQueenBee: reader.readBoolean(),
    downedMechBoss1: reader.readBoolean(),
    downedMechBoss2: reader.readBoolean(),
    downedMechBoss3: reader.readBoolean(),
    downedMechBossAny: reader.readBoolean(),
    downedPlantBoss: reader.readBoolean(),
    downedGolemBoss: reader.readBoolean(),
    downedSlimeKing: reader.readBoolean(),
    savedGoblin: reader.readBoolean(),
    savedWizard: reader.readBoolean(),
    savedMech: reader.readBoolean(),
    downedGoblins: reader.readBoolean(),
    downedClown: reader.readBoolean(),
    downedFrost: reader.readBoolean(),
    downedPirates: reader.readBoolean(),
    shadowOrbSmashed: reader.readBoolean(),
    spawnMeteor: reader.readBoolean(),
    shadowOrbCount: reader.readUInt8(),
    altarCount: reader.readInt32(),
    hardMode: reader.readBoolean(),
    afterPartyOfDoom: world.version >= 257 && reader.readBoolean(),
    invasionDelay: reader.readInt32(),
    invasionSize: reader.readInt32(),
    invasionType: reader.readInt32(),
    invasionX: reader.readFloat64(),
    slimeRainTime: reader.readFloat64(),
    sundialCooldown: reader.readUInt8(),
    tempRaining: reader.readBoolean(),
    tempRainTime: reader.readInt32(),
    tempMaxRain: reader.readFloat32(),
    oreTier1: reader.readInt32(),
    oreTier2: reader.readInt32(),
    oreTier3: reader.readInt32(),
    setBG0: reader.readUInt8(),
    setBG1: reader.readUInt8(),
    setBG2: reader.readUInt8(),
    setBG3: reader.readUInt8(),
    setBG4: reader.readUInt8(),
    setBG5: reader.readUInt8(),
    setBG6: reader.readUInt8(),
    setBG7: reader.readUInt8(),
    cloudBGActive: reader.readInt32(),
    numClouds: reader.readInt16(),
    windSpeed: reader.readFloat32(),
    anglerWhoFinishedToday: reader.readArray(reader.readInt32(), () => reader.readString),
    savedAngler: reader.readBoolean(),
    anglerQuest: reader.readInt32(),
    savedStylist: reader.readBoolean(),
    savedTaxCollector: reader.readBoolean(),
    savedGolfer: isV140 && reader.readBoolean(),
    invasionSizeStart: reader.readInt32(),
    tempCultistDelay: reader.readInt32(),
    killCount: reader.readArray(reader.readInt16(), () => reader.readInt32),
    fastForwardTimeToDawn: reader.readBoolean(),
    downedFishron: reader.readBoolean(),
    downedMartians: reader.readBoolean(),
    downedAncientCultist: reader.readBoolean(),
    downedMoonlord: reader.readBoolean(),
    downedHalloweenKing: reader.readBoolean(),
    downedHalloweenTree: reader.readBoolean(),
    downedChristmasIceQueen: reader.readBoolean(),
    downedChristmasSantank: reader.readBoolean(),
    downedChristmasTree: reader.readBoolean(),
    downedTowerSolar: reader.readBoolean(),
    downedTowerVortex: reader.readBoolean(),
    downedTowerNebula: reader.readBoolean(),
    downedTowerStardust: reader.readBoolean(),
    TowerActiveSolar: reader.readBoolean(),
    TowerActiveVortex: reader.readBoolean(),
    TowerActiveNebula: reader.readBoolean(),
    TowerActiveStardust: reader.readBoolean(),
    LunarApocalypseIsUp: reader.readBoolean(),
    tempPartyManual: reader.readBoolean(),
    tempPartyGenuine: reader.readBoolean(),
    tempPartyCooldown: reader.readInt32(),
    tempPartyCelebratingNPCs: reader.readArray(reader.readInt32(), () => reader.readInt32),
    Temp_Sandstorm_Happening: reader.readBoolean(),
    Temp_Sandstorm_TimeLeft: reader.readInt32(),
    Temp_Sandstorm_Severity: reader.readFloat32(),
    Temp_Sandstorm_IntendedSeverity: reader.readFloat32(),
    savedBartender: reader.readBoolean(),
    DD2Event_DownedInvasionT1: reader.readBoolean(),
    DD2Event_DownedInvasionT2: reader.readBoolean(),
    DD2Event_DownedInvasionT3: reader.readBoolean(),
    setBG8: Number(isV140 && reader.readUInt8()),
    setBG9: Number(isV140 && reader.readUInt8()),
    setBG10: Number(isV140 && reader.readUInt8()),
    setBG11: Number(isV140 && reader.readUInt8()),
    setBG12: Number(isV140 && reader.readUInt8()),
    combatBookWasUsed: isV140 && reader.readBoolean(),
    lanternNightCooldown: Number(isV140 && reader.readInt32()),
    lanternNightGenuine: isV140 && reader.readBoolean(),
    lanternNightManual: isV140 && reader.readBoolean(),
    lanternNightNextNightIsGenuine: isV140 && reader.readBoolean(),
    treeTopsVariations: isV140 ? reader.readArray(reader.readInt32(), () => reader.readInt32) : [],
    forceHalloweenForToday: isV140 && reader.readBoolean(),
    forceXMasForToday: isV140 && reader.readBoolean(),
    savedOreTierCopper: Number(isV140 && reader.readInt32()),
    savedOreTierIron: Number(isV140 && reader.readInt32()),
    savedOreTierSilver: Number(isV140 && reader.readInt32()),
    savedOreTierGold: Number(isV140 && reader.readInt32()),
    boughtCat: isV140 && reader.readBoolean(),
    boughtDog: isV140 && reader.readBoolean(),
    boughtBunny: isV140 && reader.readBoolean(),
    downedEmpressOfLight: isV140 && reader.readBoolean(),
    downedQueenSlime: isV140 && reader.readBoolean(),
    downedDeerclops: world.version >= 240 && reader.readBoolean(),
    unlockedSlimeBlueSpawn: isV144 && reader.readBoolean(),
    unlockedMerchantSpawn: isV144 && reader.readBoolean(),
    unlockedDemolitionistSpawn: isV144 && reader.readBoolean(),
    unlockedPartyGirlSpawn: isV144 && reader.readBoolean(),
    unlockedDyeTraderSpawn: isV144 && reader.readBoolean(),
    unlockedTruffleSpawn: isV144 && reader.readBoolean(),
    unlockedArmsDealerSpawn: isV144 && reader.readBoolean(),
    unlockedNurseSpawn: isV144 && reader.readBoolean(),
    unlockedPrincessSpawn: isV144 && reader.readBoolean(),
    combatBookVolumeTwoWasUsed: isV144 && reader.readBoolean(),
    peddlersSatchelWasUsed: isV144 && reader.readBoolean(),
    unlockedSlimeGreenSpawn: isV144 && reader.readBoolean(),
    unlockedSlimeOldSpawn: isV144 && reader.readBoolean(),
    unlockedSlimePurpleSpawn: isV144 && reader.readBoolean(),
    unlockedSlimeRainbowSpawn: isV144 && reader.readBoolean(),
    unlockedSlimeRedSpawn: isV144 && reader.readBoolean(),
    unlockedSlimeYellowSpawn: isV144 && reader.readBoolean(),
    unlockedSlimeCopperSpawn: isV144 && reader.readBoolean(),
    fastForwardTimeToDusk: isV144 && reader.readBoolean(),
    moondialCooldown: Number(isV144 && reader.readUInt8()),
  }
}
